// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZH_tool.Data;

#nullable disable

namespace ZH_tool.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119154924_FeladatTabla")]
    partial class FeladatTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZH_tool.Models.Ertekeles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ErtekelesDatuma")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LLM_Visszajelzes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MegoldasId")
                        .HasColumnType("integer");

                    b.Property<int?>("Pontszam")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MegoldasId");

                    b.ToTable("ertekelesek_tabla", (string)null);
                });

            modelBuilder.Entity("ZH_tool.Models.Feladat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FeladatCime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("GeneraltZhId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Kompetenciak")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NehezsegiSzint")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Pontozas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Temakor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("GeneraltZhId");

                    b.ToTable("feladatok_tabla", (string)null);
                });

            modelBuilder.Entity("ZH_tool.Models.GeneraltZh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GeneratedJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GenerationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ParentZhId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentZhId");

                    b.ToTable("generalt_zh_tabla", (string)null);
                });

            modelBuilder.Entity("ZH_tool.Models.Hallgato", b =>
                {
                    b.Property<string>("Neptunkod")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Neptunkod");

                    b.ToTable("hallgatok_tabla", (string)null);
                });

            modelBuilder.Entity("ZH_tool.Models.Megoldas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BekuldesDatuma")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BekuldottMegoldas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GeneraltZhId")
                        .HasColumnType("integer");

                    b.Property<string>("HallgatoNeptunkod")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("GeneraltZhId");

                    b.HasIndex("HallgatoNeptunkod");

                    b.ToTable("megoldasok_tabla", (string)null);
                });

            modelBuilder.Entity("ZH_tool.Models.Zh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeladatokSzama")
                        .HasColumnType("integer");

                    b.Property<string>("MintaZH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nehezseg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProgramozasiNyelv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemakorLeiras")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tematika")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("zh_tabla", (string)null);
                });

            modelBuilder.Entity("ZH_tool.Models.Ertekeles", b =>
                {
                    b.HasOne("ZH_tool.Models.Megoldas", "Megoldas")
                        .WithMany()
                        .HasForeignKey("MegoldasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Megoldas");
                });

            modelBuilder.Entity("ZH_tool.Models.Feladat", b =>
                {
                    b.HasOne("ZH_tool.Models.GeneraltZh", "GeneraltZh")
                        .WithMany("Feladatok")
                        .HasForeignKey("GeneraltZhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneraltZh");
                });

            modelBuilder.Entity("ZH_tool.Models.GeneraltZh", b =>
                {
                    b.HasOne("ZH_tool.Models.Zh", "ParentZh")
                        .WithMany("GeneraltZhk")
                        .HasForeignKey("ParentZhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentZh");
                });

            modelBuilder.Entity("ZH_tool.Models.Megoldas", b =>
                {
                    b.HasOne("ZH_tool.Models.GeneraltZh", "GeneraltZh")
                        .WithMany()
                        .HasForeignKey("GeneraltZhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZH_tool.Models.Hallgato", "Hallgato")
                        .WithMany("Megoldasok")
                        .HasForeignKey("HallgatoNeptunkod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneraltZh");

                    b.Navigation("Hallgato");
                });

            modelBuilder.Entity("ZH_tool.Models.GeneraltZh", b =>
                {
                    b.Navigation("Feladatok");
                });

            modelBuilder.Entity("ZH_tool.Models.Hallgato", b =>
                {
                    b.Navigation("Megoldasok");
                });

            modelBuilder.Entity("ZH_tool.Models.Zh", b =>
                {
                    b.Navigation("GeneraltZhk");
                });
#pragma warning restore 612, 618
        }
    }
}
