// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZH_tool.Data;

#nullable disable

namespace ZH_tool.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118204034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZH_tool.Models.Zh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeladatokSzama")
                        .HasColumnType("integer");

                    b.Property<string>("MintaZH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nehezseg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProgramozasiNyelv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemakorLeiras")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tematika")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("zh_tabla", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
